spring:
  datasource:
    url: jdbc:hsqldb:mem:home_delivery;sql.syntax_mys=true
    driver-class-name: org.hsqldb.jdbcDriver
    username: test_partners
    password: test_partners
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

server:
  port: 8091